name: Logger Workflow

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: Initialization
         continue-on-error: true
         run: |
           git config --global user.name miniloona
           git config --global user.email ${{ secrets.GH_MAIL }}
           git config --global credential.helper store
           echo "https://miniloona:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
       - name: Cloning Repo
         continue-on-error: true
         run: |
           git clone https://miniloona:${{ secrets.GH_TOKEN }}@github.com/miniloona/creds CREDS
       - name: Running Userbot
         timeout-minutes: 350
         continue-on-error: true
         run: |
           sudo sh ultroid.sh
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://github.com/miniloona/logger loop
              cd loop || exit 1
              echo $(TZ='Asia/Dhaka' date) >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop $(TZ='Asia/Dhaka' date)"
              git push -q https://${{ secrets.GH_TOKEN }}@github.com/miniloona/logger HEAD:main
